# -*- coding: utf-8 -*-

Automatically generated by Colab.

## Bài 1 : Tính tuổi
"""

def Tinh_Tuoi():
  namSinh = int(input ("Nhap nam sinh cua ban : "))
  tuoi = 2025 - namSinh
  print(tuoi)

Tinh_Tuoi()

"""## Bài 2 : Phương trình bậc nhất"""

def PTBN():
  a = float (input("Nhap he so a : "))
  b = float (input("Nhap he so b : "))
  if a == 0:
    if b == 0:
      print("Phuong trinh vo so nghiem")
    else:
      print("Phuong trinh vo nghiem")
  else :
    x = -b / a
    print("Phuong trinh co nghiem x = ",x)

PTBN()

"""## Bài 3 : Phương trình bậc 2"""

import math

def PTBH():
  a = float (input("Nhap he so a : "))
  b = float (input("Nhap he so b : "))
  c = float (input("Nhap he so c : "))
  if a == 0 :
    if b == 0:
      if c == 0:
        print ("Phuong trinh vo so nghiem")
      else:
        print("Phuong trinh vo nghiem")
    else :
      x = -c / b
    print("Phuong trinh co nghiem x = ",x)
  else :
    delta = b**2 - 4*a*c
    if delta < 0 :
      print("Phuong trinh vo nghiem")
    if delta == 0 :
      print("Phuong trinh co nghiem kep : x = ",-b/(2*a))
    else:
      print("Phuong trinh co hai nghiem rieng biet :")
      print("X_1 = ",(-b+math.sqrt(delta)) / (2*a))
      print("X_2 = ",(-b-math.sqrt(delta)) / (2*a))

PTBH()

"""## Bài tập 1"""

def Number_Math():
  a = int(input("Nhap so a : "))
  b = int(input("Nhap so b :"))
  print(a," + ",b," = ",a+b)
  print(a," - ",b," = ",a-b)
  print(a," * ",b," = ",a*b)
  print(a," / ",b," = ",a/b)

Number_Math()

"""## Bài tập 2"""

def Take_Keyword():
  x = "Hello World"
  ## Cách 2 : print(2:4)
  for i in range(2,5,1):
    print(x[i])

Take_Keyword()

"""# Test"""

def Length_Num(n) :
  len = 0
  while n > 0:
    len += 1
    n = int (n / 10)
    if n == 0:
      return len
      break

def Summary_Num(n) :
  sum = 0
  while n > 0:
    sum += n % 10
    n = int (n / 10)
    if n == 0:
      return sum
      break

def Maximum_Num(n):
  max = 0
  while n > 0:
    temp = n%10
    if (max < temp):
      max = temp
    n = int (n / 10)
    if n == 0:
      return max
      break

def Counting_Duplicate_Number(n):
  max = 0
  temp = str(n)
  for i in range (10) :
    count = temp.count(f"{i}")
    if max < count:
      max = count
  for i in range (10) :
    count = temp.count(f"{i}")
    if max == count:
      print(f"Chữ số {i} lặp lại nhiều nhất với {max} lần")



n = int(12340550)
len = Length_Num(n)
sum = Summary_Num(n)
max = Maximum_Num(n)
avg = sum / len

print(f"Số chữ số : {len}")
print(f"Tổng chữ số : {sum}")
print(f"Trung bình cộng các chữ số : {avg}")
print(f"Chữ số lớn nhất : {max}")
Counting_Duplicate_Number(n)