# -*- coding: utf-8 -*-

Automatically generated by Colab.

# Bài 1
"""

def CreateList(n) :
  ThisList = []
  while len(ThisList) != n:
    currentInput = input("Nhap gia tri : ")
    ThisList.append(currentInput)
  print(ThisList)

CreateList(3)

"""# Bài 2"""

def MixList ():
  a = [3,9,1,4]
  b = [2,7,4,3,2,8]

  if len(a) > len(b):
    min = len(b)
    c = a.copy()
  else:
    min = len(a)
    c = b.copy()

  for i in range (min):
    c[i] = a[i] + b[i]

  print(c)

MixList()

"""# Bài 3"""

import random

def max_measurement(Arr) :
  row = column = 0
  for i in range(len(Arr)) :
    row += 1
    column = 0
    Number_List = Arr[i]
    for x in Number_List :
      column += 1

  return row if row > column else column

def TwoD_List(m,n):
  i = j = 0
  a=[]
  while i != m :
    j = 0
    i += 1
    Number = []
    while j != n:
      j += 1
      Number.append(random.randrange(1,100))
    a.append(Number)
  return a

def export_row_K(Arr, K) :
  print(f"Ma tran thuoc dong {K} la : {Arr[K]}")

def export_column_K(Arr, K) :
  print(f"Cac gia tri thuoc cot {K} :")
  for i in range (len(Arr)) :
    Number_List = Arr[i]
    print(Number_List[K])

def Max_Sum_Column(Arr) :
  Max = 0
  Where = [0]
  for i in range (len(Arr)) :
    sum = 0
    Number_List = Arr[i]
    for x in Number_List :
      sum += x
    if sum > Max :
      Max = sum
      Where.insert(0,i)

  print(f"Tong lon nhat : {Max} tai cot o : ")
  print(Where)

def Min_Mutiple_Column (Arr):
  temp = [1 for i in range (max_measurement(Arr))]
  for i in range (len(Arr)) :
    Number_List = Arr[i]
    j=0
    for x in Number_List :
      temp[j] *= x
      j += 1
  Min = 0
  Where = [0]
  found = False
  for i in range(len(temp)):
    if Min > temp[i] or not found :
      Min = temp[i]
      Where.insert(0,i)

  print(f"Cot {Where} co tich nho nhat voi gia tri la : {Min}")

def export_value_conditional(Arr) :
  print(f"Cac phan tu thuoc dong chan va cot le : ")
  for i in range(len(Arr)):
    if i % 2 == 0 :
      Number_List = Arr[i]
      for j in range(len(Number_List)) :
        if j % 2 != 0 :
          print(Number_List[j])

def Average_g(Arr) :
  count = sum= 0
  for i in range(len(Arr)) :
    if i % 2 != 0 :
      Number_List = Arr[i]
      for x in Number_List:
        if x % 2 == 0 :
          count += 1
          sum += x
  print(f"Co {count} gia tri thoa man , tong = {sum}. Gia tri trung binh = {sum / count}")

def Average_h(Arr) :
  sum = count = 0
  for i in range(len(Arr)) :
    if i == 0 or i == len(Arr) - 1:
      for x in Arr[i] :
        count += 1
        sum += x
    else:
      Number_List = Arr[i]


Arr = TwoD_List(3,4)
print(f"Ma tran : {Arr}")
export_row_K(Arr,1)
export_column_K(Arr,2)
Max_Sum_Column(Arr)
Min_Mutiple_Column(Arr)
export_value_conditional(Arr)
Average_g(Arr)

"""# Test"""

def Index():
  cars = ['Ford', 'Mitsubishi', 'BMW', 'VW']

  print(cars[:0]) # Chạy từ trái sang phải đến khi ở chỉ số 0
  print(cars[:-2]) # Chạy từ trái sang phải đến khi ở chỉ số -2
  print(cars[::3]) # Chạy từ trái sang phải đến khi ở chỉ số 3 và chỉ nhận chỉ số chẵn
  print(cars[1:]) # Chạy từ trái sang phải từ chỉ số 0

  print(cars[-1:0:-1]) # Chạy từ phải sang trái từ chỉ số -1


Index()